import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import vm from 'node:vm';
import React from 'react';
import * as jsx from 'react/jsx-runtime';
import * as ReactDOM from 'react-dom';
import { createRoot } from 'react-dom/client';
import { JSDOM } from 'jsdom';
import { SlotCore } from '@deepseek-ai/dsh-client-ui-slots';
test('built browser panel renders updated display alias and navigates with unchanged member ID', async () => {
 const dom=new JSDOM('<html><body><div id="root"></div></body></html>',{url:'http://localhost'});
 globalThis.window=dom.window;globalThis.document=dom.window.document;globalThis.HTMLElement=dom.window.HTMLElement;globalThis.getComputedStyle=dom.window.getComputedStyle;
 globalThis.IS_REACT_ACT_ENVIRONMENT=true;
 const slots=new SlotCore();const slotName='conversation.session.header.actions';
 slots.register({name:'root',children:{[slotName]:{kind:'list',scope:'root'}}},()=>null);
 const originalPanel=()=>null;slots.register({name:slotName,id:'agent-team'},originalPanel);
 let removeAlias;let register;const state={byId:{},projectionsBySession:{lead:{values:{agentTeam:{members:[{id:'lead',name:'lead',role:'lead',phase:'active'},{id:'child',name:'backend',role:'teammate',phase:'active'}],tasks:[]},agentTeamDisplayNames:{child:'Backend — Revisão'}}}}};
 const calls=[];const passthrough=props=>props.children;const empty=()=>null;
 const primitives=new Proxy({Tooltip:passthrough,useDismissOnOutsidePointer:()=>{},useAnchoredPosition:()=>({left:0,top:0})},{get:(object,key)=>object[key]??empty});
 const api={};
 let exports;
 vm.runInNewContext(await readFile(new URL('../lib/client.js',import.meta.url),'utf8'),{window:{__ModuleLoader__:{load:spec=>{exports=spec.factory((name)=>({react:React, 'react/jsx-runtime':jsx,'react-dom':ReactDOM,'@deepseek-ai/dsh-api-session-controller':api,'@deepseek-ai/dsh-client-ui-conversation':{useConversationContext:()=>({sessionId:'lead'})},'@deepseek-ai/dsh-client-ui-primitives':primitives,'@deepseek-ai/dsh-client-ui-workspace':{useSessionOpener:()=>((id)=>calls.push(id))}}[name]??{}));}}},document:dom.window.document, getComputedStyle:dom.window.getComputedStyle, setTimeout,clearTimeout});
 const ctx={locale:{register:()=>()=>{}},sessions:{binding:()=>({session:{getSnapshot:()=>({})}}),retainInfo:()=>({getSnapshot:()=>({retainedBy:{mainView:1}})})},uiWorkspace:{openSession:arg=>calls.push(arg)},useSessions:selector=>selector(state),slots:{inject:(_name,callback)=>callback(),register:(spec,component)=>{register={...spec,component};removeAlias=slots.register(spec,component);return removeAlias;}},effect:callback=>callback()};
 exports.apply(ctx);
 assert.equal(register.priority,-10);
 assert.equal(slots.entries(slotName).length,2);
 assert.equal(slots.entriesOfSlot(slotName).length,1);
 assert.equal(slots.entriesOfSlot(slotName)[0].component,register.component);
 const root=createRoot(document.getElementById('root'));
 await React.act(async()=>{root.render(React.createElement(register.component,{sessionId:'lead',useSession:selector=>selector({}),useSessions:selector=>selector(state),useSessionStatus:()=>({status:'idle'}),openTeammate:(_root,id)=>calls.push(id),t:key=>key}));});
 await React.act(async()=>{document.querySelector('[data-team-action] button').click();});
 assert.ok(document.querySelector('[data-team-panel]').textContent.includes('Backend — Revisão'));
 state.projectionsBySession.lead.values.agentTeamDisplayNames={child:'ADMIN — Ágil'};
 await React.act(async()=>{root.render(React.createElement(register.component,{sessionId:'lead',useSession:selector=>selector({}),useSessions:selector=>selector(state),useSessionStatus:()=>({status:'idle'}),openTeammate:(_root,id)=>calls.push(id),t:key=>key}));});
 assert.ok(document.querySelector('[data-team-panel]').textContent.includes('ADMIN — Ágil'));
 assert.equal(state.projectionsBySession.lead.values.agentTeam.members[1].name,'backend');
 await React.act(async()=>{[...document.querySelectorAll('[data-team-panel] button')].find(button=>button.textContent.includes('ADMIN — Ágil')).click();});
 assert.equal(calls.at(-1),'child');
 await React.act(async()=>{root.unmount();});removeAlias();
 assert.equal(slots.entriesOfSlot(slotName)[0].component,originalPanel);dom.window.close();
});
